services:
  # Main FastAPI application
  - type: web
    name: syria-gpt-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    branch: main
    buildCommand: echo "Using Dockerfile for build"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --access-log
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: DATABASE_URL
        fromDatabase:
          name: syria-gpt-db
          property: connectionString
      - key: QDRANT_URL
        value: http://syria-gpt-qdrant:6333
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CORS_ALLOW_ALL
        value: "true"
      - key: RUNNING_IN_DOCKER
        value: "true"
      - key: DOCKER_ENV
        value: "true"

  # PostgreSQL Database
  - type: pserv
    name: syria-gpt-db
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile.db
    envVars:
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: syriagpt

  # Qdrant Vector Database
  - type: pserv
    name: syria-gpt-qdrant
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile.qdrant
    envVars:
      - key: QDRANT__SERVICE__HTTP_PORT
        value: "6333"
      - key: QDRANT__SERVICE__GRPC_PORT
        value: "6334"

databases:
  - name: syria-gpt-db
    plan: starter
    region: oregon
