services:
  # Main FastAPI application
  - type: web
    name: syria-gpt-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    branch: main
    buildCommand: echo "Using Dockerfile for build"
    startCommand: chmod +x render-deploy.sh && ./render-deploy.sh
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: DATABASE_URL
        fromDatabase:
          name: syria-gpt-db
          property: connectionString
      - key: QDRANT_URL
        value: https://qdrant.tech
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CORS_ALLOW_ALL
        value: "true"
      - key: RUNNING_IN_DOCKER
        value: "true"
      - key: DOCKER_ENV
        value: "true"
      - key: RENDER
        value: "true"

databases:
  - name: syria-gpt-db
    plan: starter
    region: oregon
